---
development:
  cloud_name: sine
  api_key: '681958435824357'
  api_secret: RfOj8jGtfhzfjzOqrrt0APTh9I8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: sine
  api_key: '681958435824357'
  api_secret: RfOj8jGtfhzfjzOqrrt0APTh9I8
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: sine
  api_key: '681958435824357'
  api_secret: RfOj8jGtfhzfjzOqrrt0APTh9I8
  enhance_image_tag: true
  static_file_support: false
